<a href="https://colab.research.google.com/github/ThusithaDeepal/predictionmodel/blob/master/prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import  Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor


In [ ]:
dataframe=pd.read_csv('/content/sample_data/data.csv')
dataset=dataframe.values
print(dataset)

[[5704 5417 9798 8613 4787 9952]
 [5491 6675 8754 8457  374 9698]
 [1063 7787 7296 7184 4665 5438]
 [8829  595 1897 3517 4599 7780]
 [7119 3277 4944 9975 8457 2515]
 [ 937  152 2410  633 6948 4642]
 [8058 1533 2081 4840 1860 2269]
 [  88 7795 4867 8306 4944 9580]
 [9688  960 2223 6902 3362 4424]
 [6811 2533 3509 9437 4427 8560]
 [2982 4713 2453 2182 7642 3778]
 [5947 6743 5978 8948 5063 5392]
 [3905 8485 6877 6111 8295 4665]
 [2444 5221 8069 7221 1691 1668]
 [9508 1943 6461 6392 6079 9722]
 [2476 2153 2192 9764  908 5353]
 [ 911 1724 2690 6235 7252 5012]
 [7805 7022 7542 8416 3557 2536]
 [9205 8922 7434 5067  294 4405]
 [6043 2892 6459 9594 1593 5882]
 [4110  364 3105 5620 5009 9699]
 [6693 8190 8347 5666 7488 1359]
 [9831 5888 7787 7984 9405 3243]
 [3326 3163 5293  793 2773 8961]
 [4466 1414 1207 4689 1787 5077]
 [6052 5110 7720 2018 8414 9924]
 [ 700 8008 1337 1101  370 7035]
 [7901 7181 1350 8952 3191 8511]
 [3089 6342 3636 4801 3249  962]
 [9596 2880 4248 6820  876 2907]
 [7885 346

In [ ]:
x=dataset[:,0:5]
print(x.shape)
y=dataset[:,-1]
y=np.reshape(y, (-1,1))
print(y.shape)

# need to scale,bt before it need to it can do in flutter
# scaler_x = MinMaxScaler()
# scaler_y = MinMaxScaler()
# print(scaler_x.fit(x))
# xscale=scaler_x.transform(x)
# print(scaler_y.fit(y))
# yscale=scaler_y.transform(y)


(100, 5)
(100, 1)


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
# 75% 25%
# print(y_test.shape)

In [ ]:
model=Sequential()
model.add(Dense(12,input_dim=5,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                72        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mse',optimizer='adam',metrics=['mse','mae'])

In [ ]:
history= model.fit(x_train,y_train,epochs=150,batch_size=20)

Epoch 1/150
4/4 [==============================] - 1s 4ms/step - loss: 86959136.0000 - mse: 86959136.0000 - mae: 8652.0201
Epoch 2/150
4/4 [==============================] - 0s 3ms/step - loss: 80890766.4000 - mse: 80890766.4000 - mae: 8357.5183
Epoch 3/150
4/4 [==============================] - 0s 4ms/step - loss: 78121366.4000 - mse: 78121366.4000 - mae: 8164.3632
Epoch 4/150
4/4 [==============================] - 0s 4ms/step - loss: 73417950.4000 - mse: 73417950.4000 - mae: 7935.4815
Epoch 5/150
4/4 [==============================] - 0s 3ms/step - loss: 73470051.2000 - mse: 73470051.2000 - mae: 7862.3488
Epoch 6/150
4/4 [==============================] - 0s 3ms/step - loss: 62703140.0000 - mse: 62703140.0000 - mae: 7218.9314
Epoch 7/150
4/4 [==============================] - 0s 3ms/step - loss: 61623554.4000 - mse: 61623554.4000 - mae: 7087.2393
Epoch 8/150
4/4 [==============================] - 0s 4ms/step - loss: 51412108.0000 - mse: 51412104.0000 - mae: 6418.6968
Epoch 9/150
4/4 

In [ ]:
xnew=np.array([[913,1072,1595,3736,5340]])
ynew= model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[ 913 1072 1595 3736 5340], Predicted=[3213.0403]


In [ ]:
model.save('/content/predtest.h5')

In [ ]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/predtest.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmp6gv5qx9i/assets


2312

In [ ]:
xnew=np.array([[913,1072,1595,3736,5340]])
ynew= modelnew.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[ 913 1072 1595 3736 5340], Predicted=[3213.0403]


In [ ]:
# print(history.history.keys())
# # "Loss"
# plt.plot(history.history['loss'])
# plt.plot(history.history['mse'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train', 'validation'], loc='upper left')
# plt.show()